import "../globals.css"
import Image from "next/image"
import background from "@/public/primaryBG.png"
import Header from "./components/Header"
import { Inter } from "next/font/google"
import { cookies } from "next/headers"
import CoachLogin from "./components/CoachLogin"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ["latin"] });

export default function CoachLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const auth = cookies().has('coachAuth')

  return (
    <html lang="es">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Squada+One&display=swap" rel="stylesheet" />
      </head>

      <body className={`${inter.className} relative font-squada h-screen grid grid-rows-[auto_1fr]`}>
        <figure className="fixed inset-0 -z-50 overflow-hidden ">
          <Image src={background} alt={"ClubApp background"} fill={true} className="-z-50" />
        </figure>

        {
          !auth ? <CoachLogin />
           : <>
            <Header />
            <main className="relative h-full">
              {children}
            </main>
          </>
        }
      </body>
    </html>
  )
}
